### PR TITLE
Add Basic Features to the Bot

### PR DESCRIPTION
**Pull request by Sabreen-Parveen**
The following functionalities are added:
-The bot introduces itself.
-Greets when a user joins the chat
-Says goodbye when a user leaves the chat
-The group members can make a to do list.

### CODE REVIEW

**Comment by weirdwiz** [comment]
@JIITODC/bot is it merge ready? Where can this be hosted?

**Comment by Ankurk99** [comment]
Do we need a goodbye message? Like how will the user see the message when they have already left the channel?

**Comment by rexagod** [comment]
Note that this PR invalidates #1 by shifting the default language from `JavaScript` to `Python`, which is not what the community agreed upon. Nevertheless, if folks want to work on a `Python` version, we can most definitely open up a separate branch for that.

**Comment by Ankurk99** [comment]
As it was struck for a long time so we decided to start the work on it and the people interested in developing and maintaining the bot were more comfortable in using python, so we decided to go with it. But yeah we can definitely work on both the bots with different branch and they can have different functionalities.

**Comment by DelusionalOptimist** [comment]
> Do we need a goodbye message? Like how will the user see the message when they have already left the channel?

The goodbye messages have been discarded. The changes will be pushed soon.

> Note that this PR invalidates #1 by shifting the default language from `JavaScript` to `Python`, which is not what the community agreed upon. Nevertheless, if folks want to work on a `Python` version, we can most definitely open up a separate branch for that.

Working on a separate branch for `python` sounds good, we can surely do this :+1:.

**Comment by DelusionalOptimist** [comment]
@weirdwiz @Ankurk99
Some updates :- 

- [x] feat: add requested features (namely: intro, welcome messages, xkcd)
<s> bug: fix unexpected behaviour of `/start`</s>
- [x] feat: add response to unknown commands 

After the above tasks are complete, the bot will be merge and deploy ready. From then on new issues will be worked upon.
As decided, these changes will be merged into a separate `python` branch. Please make a new branch so that we can change the base branch for this PR.

**Comment by weirdwiz** [comment]
Thanks for the updates :D

**Comment by rexagod** [comment]
Please change the target branch to `py` ([`master -> py`](https://github.com/JIITODC/bot/tree/py)).

**Comment by Sabreen-Parveen** [comment]
Done!

**Comment by DelusionalOptimist** [comment]
@weirdwiz This can be merged now. :smile:

**Pull request merged**
