### PR TITLE
Basic structure is ready.

### PR DESCRIPTION
**Pull request by karandevtyagi**

### CODE REVIEW

**Comment by rexagod** [comment]
Nice work! I think we should work a bit more on this pull request and add some tests to verify these features in the future. Then we should be good to merge. I'll write up the tests, although we do need to host this bot somewhere before we can test this. Heroku maybe?

**Comment by karandevtyagi** [comment]
Heroku will be good. JODC has a heroku account.

**Comment by rexagod** [comment]
Cool, let's do that! 👍🏻

**Comment by rexagod** [comment]
Maybe we can get more people involved here from the community and divide some of these peripheral tasks among them?

**Comment by aayushmau5** [comment]
Made some changes to the PR, so you don't have to write onSomeCommand(bot) for every command you make. I'm using 'fs' module, which will automatically import and run all the files present in 'command' directory. You have to make some changes to 'commands.js' files also in order to make this work. My only concern is that, if it will work on heroku or not.

**Comment by rexagod** [comment]
@aayushmau5 It should. I assume you are importing a `json` for this? Also, can you push that on your fork so we can check it out?

Ps. This should come in handy: https://www.npmjs.com/package/babel-plugin-inline-json-import

**Comment by aayushmau5** [comment]
https://github.com/aayushmau5/bot 
Here's the fork. Let me see your suggestion also.Thanks.

**Comment by rexagod** [comment]
LGTM. Can you deploy your fork on your local and check whether it's working as intended?

**Comment by aayushmau5** [comment]
Yup. It is working on my local machine. Should i deploy it using heroku and check ?

**Comment by rexagod** [comment]
We do have to deploy this to heroku anyway, for every time a PR comes through (we'll write a workflow for that soon) we'll have to mock calls for testing if everything is working fine, so go ahead! 👍🏻

**Pull request closed without merging**
